name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
            env: JRUBY_OPTS="--debug -X+O"
          - os: ubuntu
            ruby: head
            experimental: true
    
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    
    - name: Install dependencies
      run: ${{matrix.env}} bundle install
    
    - name: Installing dependencies (ubuntu)
      if: matrix.os == 'ubuntu'
      run: |
        sudo systemctl stop mysql
        sudo apt-get install libmariadb-dev
    
    - name: Run tests
      timeout-minutes: 5
      run: |
        ${{matrix.env}} bundle exec rspec
